### ISSUE TITLE
Device type -i instead of -e

### ISSUE THREAD

**Issue by gjkunde** [Avnet/bdf#6]
Hello,

I am trying to use new v2 bdfs in the Vitis chain with Vivado 2020.3 in 18.04 LTD, importing my work from Vivado 2018.3:

I get a device type mismatch because the pdf is specifying the -i not the -e in previous files, I
hacked that but there is still the complaint about locked ip and bus width changes with respect
to v2 1.0 ..

Any guidance would be greatly appreciated, thank you

**Comment by zedman2000** [comment]
Hi there, you will want to access the support forums on Element 14.
https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums/ultra96-hardware-design-forum
And as a parting gift, some basic information:
The I vs E is intentional.  We updated the BDF to target the I grade as we now sell an I grade part and you can build I grade and use it on E grade.  You typically will get exactly that behavior when importing a design.  It is generally good practice to rebuild the design using TCL in the new tools - which is what we support in our repository, otherwise you have to go into each IP and update them.

Also, do you mean the 2020.2 tools?  2020.3 is not out at this time.
