### ISSUE TITLE
Does this support Vivado 2019.2?

### ISSUE THREAD

**Issue by Jefferson111** [Avnet/bdf#7]

**Comment by narrucmot** [comment]
Hello,
Yes, this bdf repository supports Vivado 2019.2.  This repository was created circa 2018.3 and supports every Vivado version since then.

We don't actively monitor this site for user support, so in the future, for your benefit and for the entire user community, if you have any questions about designing in Vivado for any of the Avnet SOMs or SBCs please post your questions to the user forums on element14.com (https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums/places?filterID=all&sortKey=all~recentActivityDateDesc).

--Tom
